## Problem 1.6 String Compression
### Implement a method to perform basic string compression using the counts of repeated characters. For example, the string aabcccccaaa would become a2b1c5a3. If the "compressed" string would not become smaller than the original string, your method should return the original string. You can assume the string has only uppercase and lowercase letters (a - z).

In [ ]:
S = "aabcccccaa"

In [ ]:
S = "abc"

In [ ]:
S = "aabbcccccccccdd"

In [ ]:
counter = 1
LS = []
lenS = len(S)
for i in range(lenS):
    if S[i] == S[i-1]:
        counter += 1
    else:
        LS.append(S[i-1]+str(counter))
#         LS.append(counter)
        counter = 1
        
LS.append(S[lenS-1]+str(counter))
# LS.append(counter)
newS = "".join(LS)

if len(newS) < lenS:
    print(newS)
else:
    print(S)


## Problem 1.7 Rotate Matrix
### Given an image represented by an NxN matrix, where each pixel in the image is 4 bytes, write a method to rotate the image by 90 degrees. (an you do this in place?

In [4]:
A = [[1,2,3], [1,2,3], [1,2,3]]
print(A)

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]


In [ ]:
A = [[1,1,2,2], [3,3,4,4], [5,5,6,6], [7,7,8,8]]
print(A)

In [11]:
A = [[1,2,3,4], [5,6,7,8], [-1,-2,-3,-4], [-5,-6,-7,-8]]
print(A)

[[1, 2, 3, 4], [5, 6, 7, 8], [-1, -2, -3, -4]]


In [ ]:
len(A)

In [ ]:
matrilLen = len(A)

# transpose Step
for i in range(matrilLen):
    for j in range(i):
        A[i][j], A[j][i] = A[j][i], A[i][j]
        
# reverse row step
for i in range(matrilLen):
    for j in range(int(matrilLen/2)):
        A[i][j], A[i][matrilLen-j-1] = A[i][matrilLen-j-1], A[i][j]


## Problem 1.8 Zero Matrix
### Write an algorithm such that if an element in an MxN matrix is 0, its entire row and column are set to O

In [61]:
import numpy as np 
A = np.array([[1,1,2,2], [3,3,4,4], [0,5,6,6], [7,7,8,8]])  #NXN

print(A)
len(A[0]) #column len

[[1 1 2 2]
 [3 3 4 4]
 [0 5 6 6]
 [7 7 8 8]]


4

In [67]:
A = np.array([[1,1,2,2], [3,0,4,4], [5,5,6,6]])  #NXN

print(A)


[[1 1 2 2]
 [3 0 4 4]
 [5 5 6 6]]


In [68]:
ListR = []
ListC = []
for i in range(len(A)):
    for j in range(len(A[0])):
        if A[i][j] == 0:
            ListR.append(i)
            ListC.append(j)

for i in ListR:
    for j in range(len(A[0])):
        A[i][j] = 0
        
for i in range(len(A)):
    for j in ListC:
        A[i][j] = 0

In [69]:
import numpy as np

print(A)


[[1 0 2 2]
 [0 0 0 0]
 [5 0 6 6]]


## Problem 1.9 String Rotation
### Assume you have a method isSubstring which checks if one word is a substring of another. Given two strings, s1 and s2, write code to check if s2 is a rotation of s1 using only one call to isSubstring (e.g., "waterbottle" is a rotation of "erbottlewat").

In [77]:
s1 = "waterbottle"
s2 = "erbottlewat"
s1[1]

'a'

In [78]:
def is_substring(string, sub):
    return string.find(sub) != -1

def string_rotation(s1, s2):
    if len(s1) == len(s2) != 0:
        return is_substring(s1 + s1, s2)
    return False

print(string_rotation(s1,s2))

True
